// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficMonitor.Infrastructure.Persistence;

#nullable disable

namespace TrafficMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(TrafficMonitorDbContext))]
    [Migration("20260416145319_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficMonitor.Domain.Entities.TrafficEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("camera_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("traffic_events", (string)null);
                });

            modelBuilder.Entity("TrafficMonitor.Domain.Entities.TrafficEvent", b =>
                {
                    b.OwnsMany("TrafficMonitor.Domain.ValueObjects.Detection", "Detections", b1 =>
                        {
                            b1.Property<int>("TrafficEventId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal>("Confidence")
                                .HasPrecision(5, 4);

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.HasKey("TrafficEventId", "__synthesizedOrdinal");

                            b1.ToTable("traffic_events");

                            b1
                                .ToJson("detections")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrafficEventId");

                            b1.OwnsOne("TrafficMonitor.Domain.ValueObjects.BoundingBox", "BoundingBox", b2 =>
                                {
                                    b2.Property<int>("DetectionTrafficEventId");

                                    b2.Property<int>("Detection__synthesizedOrdinal");

                                    b2.Property<decimal>("Height")
                                        .HasPrecision(7, 2);

                                    b2.Property<decimal>("Width")
                                        .HasPrecision(7, 2);

                                    b2.Property<decimal>("X")
                                        .HasPrecision(7, 2);

                                    b2.Property<decimal>("Y")
                                        .HasPrecision(7, 2);

                                    b2.HasKey("DetectionTrafficEventId", "Detection__synthesizedOrdinal");

                                    b2.ToTable("traffic_events");

                                    b2.WithOwner()
                                        .HasForeignKey("DetectionTrafficEventId", "Detection__synthesizedOrdinal");
                                });

                            b1.Navigation("BoundingBox")
                                .IsRequired();
                        });

                    b.Navigation("Detections");
                });
#pragma warning restore 612, 618
        }
    }
}
